#!/usr/bin/env node
/**
 * Slop Check — duplication + complexity gate (local, 0-dep, Node 18+)
 * Học "The Slop Should Not Be Tolerated" (HackerNoon 2026-09-12) — KN-047:
 *   "code can pass every behavior test and still be miserable to maintain"
 *   SlopCodeBench (arXiv 2603.24755v2): 3/4 agent runs phình complexity khi extend code.
 *
 * Usage:
 *   node scripts/slop-check.mjs <files...>          # GATE mode — exit 1 nếu findings, exit 2 nếu 0 file
 *   node scripts/slop-check.mjs --scan [roots...]   # AUDIT mode — quét roots mặc định, exit 0 (báo cáo)
 * Flags: --min-lines 8 · --max-func 80 · --max-cc 12 · --top 10 · --json · --strict
 *
 * Checks (heuristic — không thay thế review người):
 *   1. Duplication  — block ≥ N dòng giống nhau (cùng file hoặc cross-file;
 *      block kề nhau cách < N dòng trong cùng file không tính), bỏ dòng trivial/comment
 *   2. Function size — block function > max-func dòng (brace-depth scanner)
 *   3. Complexity   — cyclomatic-lite > max-cc (if/else/for/while/case/catch/&&/||/??)
 *
 * Limits (đã biết): scanner chỉ đo block depth-0 — class/nested closure KHÔNG được đo;
 * string/regex strip là heuristic; minified/generated tự skip theo marker 3 dòng đầu.
 */
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, '..');

const EXT_OK = new Set(['.js', '.mjs', '.ts']);
const SKIP_DIRS = new Set(['node_modules', 'vendor', '.git', '.claude', '.disabled', 'bin', 'obj', 'publish', 'test-results', 'playwright-report', '.agent']);
const GEN_MARKERS = ['DO NOT EDIT', 'generated by', 'auto-generated'];
const DEFAULT_ROOTS = ['www', 'scripts', '.github/harness/scripts', '.agent/scripts'];

const BOOL_FLAGS = new Set(['scan', 'strict', 'json']);

function parseArgs(argv) {
  const out = { files: [], roots: [], flags: {} };
  for (let i = 0; i < argv.length; i++) {
    const a = argv[i];
    if (a.startsWith('--')) {
      const key = a.slice(2);
      if (BOOL_FLAGS.has(key)) { out.flags[key] = true; continue; }
      const next = argv[i + 1];
      if (next && !next.startsWith('--')) { out.flags[key] = next; i++; } else out.flags[key] = true;
    } else if (out.flags.scan) out.roots.push(a);
    else out.files.push(a);
  }
  return out;
}

function walkDir(dir, acc) {
  let entries;
  try { entries = fs.readdirSync(dir, { withFileTypes: true }); } catch { return acc; }
  for (const e of entries) {
    const full = path.join(dir, e.name);
    if (e.isDirectory()) {
      if (!SKIP_DIRS.has(e.name)) walkDir(full, acc);
    } else if (EXT_OK.has(path.extname(e.name)) && !e.name.endsWith('.min.js')) {
      acc.push(full);
    }
  }
  return acc;
}

function readScannable(file) {
  const text = fs.readFileSync(file, 'utf8');
  const head = text.split('\n', 3).join('\n');
  if (GEN_MARKERS.some((m) => head.includes(m))) return null;
  return text;
}

const normalize = (line) => line.trim().replace(/\s+/g, ' ');
function isTrivial(norm) {
  if (!norm || norm.length < 4) return true;
  if (/^[{}()[\];,]+$/.test(norm)) return true;
  return /^(\/\/|\/\*|\*|-->|<!--)/.test(norm);
}

// ---------- Check 1: Duplication ----------
function buildStream(filesData) {
  const stream = [];
  filesData.forEach((fd, f) => {
    fd.lines.forEach((raw, i) => {
      const norm = normalize(raw);
      if (!isTrivial(norm)) stream.push({ f, i, norm });
    });
  });
  return stream;
}

function sameBlock(a, b, minLines) {
  return a.f === b.f && Math.abs(a.i - b.i) < minLines;
}

function extendRun(stream, ia, ib, minLines) {
  let len = 1;
  while (true) {
    const ea = stream[ia + len];
    const eb = stream[ib + len];
    if (!ea || !eb) break;
    if (ea.f !== stream[ia + len - 1].f || eb.f !== stream[ib + len - 1].f) break; // không vượt biên file
    if (ea.norm !== eb.norm) break;
    if (sameBlock(ea, eb, minLines)) break;
    len++;
  }
  return len;
}

function coverageOf(run) {
  return Math.max(run.a.i, run.b.i) + run.len - Math.min(run.a.i, run.b.i);
}

function containedIn(run, kept) {
  return kept.some((k) =>
    k.a.f === run.a.f && k.b.f === run.b.f &&
    k.a.i <= run.a.i && k.b.i <= run.b.i &&
    k.a.i + k.len > run.a.i + run.len - 1 && k.b.i + k.len > run.b.i + run.len - 1);
}

function findDuplication(filesData, minLines, top) {
  const stream = buildStream(filesData);
  const byNorm = new Map();
  stream.forEach((p, si) => {
    if (!byNorm.has(p.norm)) byNorm.set(p.norm, []);
    byNorm.get(p.norm).push(si);
  });
  const candidates = [];
  for (const group of byNorm.values()) {
    if (group.length < 2 || group.length > 60) continue;
    for (let x = 0; x < group.length; x++) {
      for (let y = x + 1; y < group.length; y++) {
        const ia = group[x], ib = group[y];
        if (sameBlock(stream[ia], stream[ib], minLines)) continue;
        const len = extendRun(stream, ia, ib, minLines);
        if (len >= minLines) candidates.push({ a: stream[ia], b: stream[ib], len });
      }
    }
  }
  candidates.sort((x, y) => coverageOf(y) - coverageOf(x));
  const kept = [];
  for (const run of candidates) {
    if (containedIn(run, kept)) continue;
    kept.push(run);
    if (kept.length >= top * 3) break;
  }
  return kept.slice(0, top).map((run) => ({
    type: 'duplication',
    lines: run.len,
    a: { file: filesData[run.a.f].rel, line: run.a.i + 1 },
    b: { file: filesData[run.b.f].rel, line: run.b.i + 1 },
    preview: run.a.norm.slice(0, 72),
  }));
}

// ---------- Check 2+3: Function size & complexity ----------
const FN_HEADER = /(?:function\s+[\w$]+|=>|[\w$.]+\s*\([^)]*\)\s*\{?\s*$)/;
const FN_KEYWORDS = /^(if|for|while|switch|catch|else|do|return|throw)\b/;
const COMPLEXITY = /\bif\b|\belse\b|\bfor\b|\bwhile\b|\bcase\b|\bcatch\b|\?\?|&&|\|\||\?/g;

function strippedLine(raw) {
  return raw
    .replace(/'[^']*'/g, '""').replace(/"[^"]*"/g, '""')
    .replace(/`[^`]*`/g, '``')
    .replace(/(^|[=(:,!&|{;]\s*)\/(?![/*])(?:[^\/\\\n[]|\\.|\[(?:[^\]\\]|\\.)*\])+\/[gimsuy]*/g, '$1RE')
    .replace(/\/\/.*$/, '');
}
function bracesOf(stripped) {
  let open = 0, close = 0;
  for (const ch of stripped) { if (ch === '{') open++; else if (ch === '}') close++; }
  return [open, close];
}
function fnNameOf(raw) {
  const m = raw.match(/function\s+([\w$]+)/) || raw.match(/(?:const|let|var)\s+([\w$]+)\s*=/) ||
    raw.match(/^\s*(?:async\s+)?([\w$]+)\s*\(/);
  return m ? m[1] : '(anonymous)';
}

function scanFunctions(lines, rel, maxFunc, maxCC) {
  const findings = [];
  let depth = 0, start = -1, name = '';
  lines.forEach((raw, i) => {
    const stripped = strippedLine(raw);
    const [open, close] = bracesOf(stripped);
    const before = depth;
    depth += open - close;
    const header = stripped.trim();
    if (before === 0 && depth > 0 && FN_HEADER.test(header) && !FN_KEYWORDS.test(header)) {
      start = i; name = fnNameOf(raw);
    } else if (before > 0 && depth === 0 && start !== -1) {
      const len = i - start + 1;
      if (len >= 10) pushFnFinding(findings, { lines, rel, start, len, name, maxFunc, maxCC });
      start = -1;
    }
  });
  if (start !== -1) {
    const len = lines.length - start;
    if (len >= 10) pushFnFinding(findings, { lines, rel, start, len, name, maxFunc, maxCC });
  }
  return findings;
}

function pushFnFinding(findings, c) {
  const { lines, rel, start, len, name, maxFunc, maxCC } = c;
  if (len > maxFunc) {
    findings.push({ type: 'size', file: rel, line: start + 1, fn: name, lines: len, max: maxFunc });
  }
  const body = lines.slice(start, start + len).map(strippedLine).join('\n');
  const cc = 1 + (body.match(COMPLEXITY) || []).length;
  if (cc > maxCC) {
    findings.push({ type: 'complexity', file: rel, line: start + 1, fn: name, cc, max: maxCC });
  }
}

// ---------- Report ----------
function printReport(result, flags) {
  if (flags.json) { console.log(JSON.stringify(result, null, 2)); return; }
  const { files, dup, fnFindings, minLines, maxFunc, maxCC } = result;
  console.log(`🧹 Slop Check — ${files} file · dup ≥${minLines} dòng · fn ≤${maxFunc} dòng · CC ≤${maxCC}`);
  if (dup.length) {
    console.log(`\n⚠️  Duplication (${dup.length} block):`);
    for (const d of dup) {
      console.log(`   • ${d.lines} dòng ×2 — ${d.a.file}:${d.a.line} ↔ ${d.b.file}:${d.b.line}`);
      console.log(`     └ ${d.preview}`);
    }
  }
  if (fnFindings.length) console.log('\n⚠️  Function metrics:');
  for (const f of fnFindings) {
    const detail = f.type === 'size' ? `${f.lines} dòng (max ${f.max})` : `CC ${f.cc} (max ${f.max})`;
    console.log(`   • [${f.type}] ${f.file}:${f.line} ${f.fn}() — ${detail}`);
  }
  const total = dup.length + fnFindings.length;
  if (total === 0) console.log('\n✅ Clean — không phát hiện slop.');
  else console.log(`\n❌ ${total} findings — fix hoặc justify trước khi Done (Slop Gate · KN-047)`);
}

function parseThreshold(flags, key, fallback) {
  const n = parseInt(flags[key], 10);
  return Number.isFinite(n) && n > 0 ? n : fallback;
}

function collectTargets(files, roots, isScan) {
  if (!isScan) return files.map((f) => path.resolve(ROOT, f));
  const scanRoots = roots.length ? roots : DEFAULT_ROOTS;
  return scanRoots.flatMap((r) => walkDir(path.resolve(ROOT, r), []));
}

function loadFilesData(targets) {
  const filesData = [];
  const seen = new Set();
  for (const abs of targets) {
    const key = path.resolve(abs);
    if (seen.has(key)) continue;
    seen.add(key);
    let text;
    try { text = readScannable(abs); } catch { console.warn(`[skip] không đọc được: ${abs}`); continue; }
    if (text === null) continue;
    filesData.push({ rel: path.relative(ROOT, abs).replace(/\\/g, '/'), lines: text.split('\n') });
  }
  return filesData;
}

function main() {
  const { files, roots, flags } = parseArgs(process.argv.slice(2));
  const opts = {
    minLines: parseThreshold(flags, 'min-lines', 8),
    maxFunc: parseThreshold(flags, 'max-func', 80),
    maxCC: parseThreshold(flags, 'max-cc', 12),
    top: parseThreshold(flags, 'top', 10),
  };
  const isScan = !!flags.scan;
  if (!isScan && files.length === 0) {
    console.error('❌ GATE mode cần ít nhất 1 file — vd: node scripts/slop-check.mjs <changed files>');
    console.error('   (quét toàn cục dùng --scan — audit mode, exit 0; gate fail-closed khi 0 file)');
    process.exit(2);
  }
  const filesData = loadFilesData(collectTargets(files, roots, isScan));
  if (!isScan && filesData.length === 0) {
    console.error('❌ 0 file đọc được — kiểm tra lại path (fail-closed, exit 2)');
    process.exit(2);
  }
  const dup = findDuplication(filesData, opts.minLines, opts.top);
  const fnFindings = filesData.flatMap((fd) => scanFunctions(fd.lines, fd.rel, opts.maxFunc, opts.maxCC));
  printReport({ files: filesData.length, ...opts, dup, fnFindings }, flags);
  const failed = dup.length + fnFindings.length > 0;
  const auditPass = isScan && !flags.strict;
  process.exit(failed && !auditPass ? 1 : 0);
}

main();
